// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForCreateOrderDish implements pgx.CopyFromSource.
type iteratorForCreateOrderDish struct {
	rows                 []CreateOrderDishParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateOrderDish) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateOrderDish) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderID,
		r.rows[0].DishID,
		r.rows[0].Quantity,
		r.rows[0].Price,
	}, nil
}

func (r iteratorForCreateOrderDish) Err() error {
	return nil
}

func (q *Queries) CreateOrderDish(ctx context.Context, arg []CreateOrderDishParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order_dish"}, []string{"order_id", "dish_id", "quantity", "price"}, &iteratorForCreateOrderDish{rows: arg})
}
