// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dish struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Picture   string      `json:"picture"`
	Price     int64       `json:"price"`
	CreatedAt int64       `json:"created_at"`
	UpdatedAt int64       `json:"updated_at"`
	DeletedAt pgtype.Int8 `json:"deleted_at"`
}

type Order struct {
	ID         int64 `json:"id"`
	TotalPrice int64 `json:"total_price"`
	CreatedAt  int64 `json:"created_at"`
	UpdatedAt  int64 `json:"updated_at"`
}

type OrderDish struct {
	ID       int64 `json:"id"`
	OrderID  int64 `json:"order_id"`
	DishID   int64 `json:"dish_id"`
	Quantity int32 `json:"quantity"`
	Price    int64 `json:"price"`
}

type User struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}
